======OBJECT = WWPBaseObjects.Module === WWPBase Objects=====
<Object parentGuid="afa47377-41d5-4ae8-9755-6f53150aa361" user="" versionDate="2015-09-23T17:07:54.0000000Z" lastUpdate="2015-09-23T13:26:28.0000000Z" checksum="66158d8a8855ca0b324e9ed5d6bdbd68" fullyQualifiedName="WWPBaseObjects" guid="f952860a-9553-4095-82c8-dedaadd8cf64" name="WWPBaseObjects" type="c88fffcd-b6f8-0000-8fec-00b5497e2117" description="WWPBase Objects">
  <Part type="a5e6a251-2df0-44d8-adab-1da237574326">
    <Properties />
  </Part>
  <Part type="babf62c5-0111-49e9-a1c3-cc004d90900a">
    <Properties />
  </Part>
  <Properties><Property><Name>Name</Name><Value>WWPBaseObjects</Value></Property><Property><Name>IsDefault</Name><Value>False</Value></Property></Properties>
</Object>
====== PROPERTIES =======
FolderType -> c88fffcd-b6f8-0000-8fec-00b5497e2117
FolderId -> 1
Name -> WWPBaseObjects
IsDefault -> False
