======OBJECT = GLParametros.Module === GLParametros=====
<Object parentGuid="afa47377-41d5-4ae8-9755-6f53150aa361" user="EALMEIDANBK\Enrique" versionDate="2016-05-17T17:27:35.0000000Z" lastUpdate="2016-05-17T17:17:16.0000000Z" checksum="2898dc6767d6f91780bbeadbdbe94e7b" fullyQualifiedName="GLParametros" guid="7df0eab8-ce56-424e-8f9d-265f44af3958" name="GLParametros" type="c88fffcd-b6f8-0000-8fec-00b5497e2117" description="GLParametros">
  <Part type="a5e6a251-2df0-44d8-adab-1da237574326">
    <Properties />
  </Part>
  <Part type="babf62c5-0111-49e9-a1c3-cc004d90900a">
    <Properties />
  </Part>
  <Properties><Property><Name>Name</Name><Value>GLParametros</Value></Property><Property><Name>IsDefault</Name><Value>False</Value></Property></Properties>
</Object>
====== PROPERTIES =======
FolderType -> c88fffcd-b6f8-0000-8fec-00b5497e2117
FolderId -> 1
Name -> GLParametros
IsDefault -> False
