======OBJECT = MasterPage.Module === Master Page=====
<Object parentGuid="afa47377-41d5-4ae8-9755-6f53150aa361" user="" versionDate="2016-04-12T17:34:01.0000000Z" lastUpdate="2016-04-06T17:19:09.0000000Z" checksum="f32e6bbd9818e9425354d01a34bd1c28" fullyQualifiedName="MasterPage" guid="753a1d10-de36-4506-8688-c97531e0a839" name="MasterPage" type="c88fffcd-b6f8-0000-8fec-00b5497e2117" description="Master Page">
  <Part type="a5e6a251-2df0-44d8-adab-1da237574326">
    <Properties />
  </Part>
  <Part type="babf62c5-0111-49e9-a1c3-cc004d90900a">
    <Properties />
  </Part>
  <Properties><Property><Name>Name</Name><Value>MasterPage</Value></Property><Property><Name>IsDefault</Name><Value>False</Value></Property></Properties>
</Object>
====== PROPERTIES =======
FolderType -> c88fffcd-b6f8-0000-8fec-00b5497e2117
FolderId -> 1
Name -> MasterPage
IsDefault -> False
