======OBJECT = MOD_Objetivos.Module === MOD_Objetivos=====
<Object parentGuid="afa47377-41d5-4ae8-9755-6f53150aa361" user="" versionDate="2016-03-14T02:22:11.0000000Z" lastUpdate="2016-03-14T02:16:44.0000000Z" checksum="4a2358a8aacbbd2dd596d8d70435195d" fullyQualifiedName="MOD_Objetivos" guid="c036e3cd-eb7f-46d9-85ca-468929a7182a" name="MOD_Objetivos" type="c88fffcd-b6f8-0000-8fec-00b5497e2117" description="MOD_Objetivos">
  <Part type="a5e6a251-2df0-44d8-adab-1da237574326">
    <Graph ActiveLayerId="ebfa81c2-8b3c-46bd-ae59-5d968336772e">
      <Layers>
        <Layer Id="ebfa81c2-8b3c-46bd-ae59-5d968336772e">
          <Nodes>
            <ModuleNode KBObjectReference="c88fffcd-b6f8-0000-8fec-00b5497e2117-MOD_Objetivos" Bounds="-38.00001 323.7009 149.9999 50.8252" Expanded="True" />
            <ModuleNode KBObjectReference="c88fffcd-b6f8-0000-8fec-00b5497e2117-MOD_Global" Bounds="12.47471 104.8688 150 32.00001" Expanded="False" />
            <ModuleNode KBObjectReference="c88fffcd-b6f8-0000-8fec-00b5497e2117-MOD_Solicitudes" Bounds="760.1594 186.9023 150.0001 32.00002" Expanded="False" />
            <ModuleNode KBObjectReference="c88fffcd-b6f8-0000-8fec-00b5497e2117-GLFeriados" Bounds="573.0438 378.9453 150.0001 32.00003" Expanded="False" />
            <ModuleNode KBObjectReference="c88fffcd-b6f8-0000-8fec-00b5497e2117-MOD_Horas" Bounds="380.9735 -16 150 32" Expanded="False" />
            <ModuleNode KBObjectReference="c88fffcd-b6f8-0000-8fec-00b5497e2117-MD" Bounds="86.52252 8.863272 150 32" Expanded="False" />
            <ModuleNode KBObjectReference="c88fffcd-b6f8-0000-8fec-00b5497e2117-MOD_Proyectos" Bounds="248.1311 367.2327 150 32.00003" Expanded="False" />
          </Nodes>
        </Layer>
      </Layers>
    </Graph>
    <Properties><Property><Name>IsDefault</Name><Value>False</Value></Property></Properties>
  </Part>
  <Part type="babf62c5-0111-49e9-a1c3-cc004d90900a">
    <Properties />
  </Part>
  <Properties><Property><Name>Name</Name><Value>MOD_Objetivos</Value></Property><Property><Name>IsDefault</Name><Value>False</Value></Property></Properties>
</Object>
====== PROPERTIES =======
FolderType -> c88fffcd-b6f8-0000-8fec-00b5497e2117
FolderId -> 1
Name -> MOD_Objetivos
IsDefault -> False
