======OBJECT = MOD_Costos.Module === MOD_Costos=====
<Object parentGuid="afa47377-41d5-4ae8-9755-6f53150aa361" user="" versionDate="2016-03-15T17:55:23.0000000Z" lastUpdate="2016-03-15T16:28:13.0000000Z" checksum="cc05b3325fc5e2e0cd56fb42f6ca5e36" fullyQualifiedName="MOD_Costos" guid="369d3627-bc9f-467c-8d20-e200def4955e" name="MOD_Costos" type="c88fffcd-b6f8-0000-8fec-00b5497e2117" description="MOD_Costos">
  <Part type="a5e6a251-2df0-44d8-adab-1da237574326">
    <Properties />
  </Part>
  <Part type="babf62c5-0111-49e9-a1c3-cc004d90900a">
    <Properties />
  </Part>
  <Properties><Property><Name>Name</Name><Value>MOD_Costos</Value></Property><Property><Name>IsDefault</Name><Value>False</Value></Property></Properties>
</Object>
====== PROPERTIES =======
FolderType -> c88fffcd-b6f8-0000-8fec-00b5497e2117
FolderId -> 1
Name -> MOD_Costos
IsDefault -> False
