======OBJECT = GLUtilitarios.Module === GLUtilitarios=====
<Object parentGuid="afa47377-41d5-4ae8-9755-6f53150aa361" user="EALMEIDANBK\Enrique" versionDate="2016-05-17T17:27:35.0000000Z" lastUpdate="2016-05-17T17:17:07.0000000Z" checksum="bb6f88c35e0942905aa7d930ced020f6" fullyQualifiedName="GLUtilitarios" guid="f27aa9d3-b7b9-40d8-9b88-beff0e755318" name="GLUtilitarios" type="c88fffcd-b6f8-0000-8fec-00b5497e2117" description="GLUtilitarios">
  <Part type="a5e6a251-2df0-44d8-adab-1da237574326">
    <Properties />
  </Part>
  <Part type="babf62c5-0111-49e9-a1c3-cc004d90900a">
    <Properties />
  </Part>
  <Properties><Property><Name>Name</Name><Value>GLUtilitarios</Value></Property><Property><Name>IsDefault</Name><Value>False</Value></Property></Properties>
</Object>
====== PROPERTIES =======
FolderType -> c88fffcd-b6f8-0000-8fec-00b5497e2117
FolderId -> 1
Name -> GLUtilitarios
IsDefault -> False
