======OBJECT = MOD_Global.Module === MOD_Global=====
<Object parentGuid="afa47377-41d5-4ae8-9755-6f53150aa361" user="" versionDate="2016-03-15T19:42:43.0000000Z" lastUpdate="2016-03-15T19:00:05.0000000Z" checksum="832d4cda56fd18f076a55baad1176401" fullyQualifiedName="MOD_Global" guid="89119908-4f89-4187-8ed5-13e0298fe916" name="MOD_Global" type="c88fffcd-b6f8-0000-8fec-00b5497e2117" description="MOD_Global">
  <Part type="a5e6a251-2df0-44d8-adab-1da237574326">
    <Properties />
  </Part>
  <Part type="babf62c5-0111-49e9-a1c3-cc004d90900a">
    <Properties />
  </Part>
  <Properties><Property><Name>Name</Name><Value>MOD_Global</Value></Property><Property><Name>IsDefault</Name><Value>False</Value></Property></Properties>
</Object>
====== PROPERTIES =======
FolderType -> c88fffcd-b6f8-0000-8fec-00b5497e2117
FolderId -> 1
Name -> MOD_Global
IsDefault -> False
